### ISSUE TITLE
Multi class Training without images?

### ISSUE THREAD

**Issue by shkapo7** [mariya12290/VoxelNet_MultiClass#2]
Hi @mariya12290 thanks for your work !!! I was wondering how would one go about training without image data. I have a custom annotated dataset that is annotated like kitti and I wanted to train voxelnet on that but I don't know how to proceed. Also could it possible to train for car and pedestrian at once? And there is one last thing I wondered, I labeled the LIDAR data using https://github.com/ziliHarvey/smart-annotation-pointrcnn, so I am guessing the labels are in LIDAR cord. so I do not need the calibration matrices right? I could just replaces values by 1 in the calib matrices and still train the model?

**Comment by mariya12290** [comment]
Hello @user-2 To train voxelnet model just using LiDAR data, you need to  make lots of changes in code base and make sure the changes are correct in each and every steps of training, I mean until  the data is fed into a model, some times, it might also  be possible that, incorrect data or incorrect ground truth is fed into a mode. If the ground truths are in LiDAR CS, you do not need any kind of calibration matrices. I even trained my model on data in LiDAR CS, but it had a bug in the code.
